### ISSUE TITLE
Update RAG indexing pipeline

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant-usecase-RAG#10]
```[tasklist]
### Tasks
- [ ] Implement Load component using LlamaIndex
- [ ] Implement clean data component (optional)
- [ ] Further generalize chunk data component
- [ ] Further generalize embedding component
```
