### ISSUE TITLE
Expand the weaviate retrieval component

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant-usecase-RAG#52]
We should expand the weaviate retrieval component to leverage more of the built-in Weaviate functionality:
- Make embeddings optional
- Support hybrid search
- Support reranking
```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/69
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/70
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/71
```
