### ISSUE TITLE
RAG evaluation use case

### ISSUE THREAD

**Issue by RobbeSneyders** [ml6team/fondant-usecase-RAG#8]
```[tasklist]
### Tasks
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/10
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/11
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/9
- [ ] Write content for publicity
``` 

```[tasklist]
### [Update RAG indexing pipeline](https://github.com/ml6team/fondant-usecase-RAG/issues/10)
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/13
- [ ] Implement clean data component (optional)
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/14
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/15
``` 

```[tasklist]
### [Create RAG evaluation pipeline](https://github.com/ml6team/fondant-usecase-RAG/issues/11)
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/16
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/17
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/18
- [ ] https://github.com/ml6team/fondant-usecase-RAG/issues/19
```

**Comment by RobbeSneyders** [comment]
Proposal for the RAG evaluation loop with the different frameworks that we could use.

![Image](https://github.com/ml6team/fondant-usecase-RAG/assets/20990866/72613dfc-57b4-4ff4-9de1-0285264c81d8)

I added the data explorer at steps where I think it would be useful  @PhilippeMoussalli. It just shows the data I think would be valuable at each step. Visualization should be refined of course, but this can serve as validation that we are building the necessary functionality and as a starting point to discuss it further.

Some notes on the frameworks:
- [LlamaIndex](https://github.com/run-llama/llama_index) for loading provides both LlamaIndex and LangChain loaders. The result is documents, not nodes. We'll have to see what data other than the text we want to serialize. As far as I can see, the loaders cannot handle out of memory data, but for RAG this should probably not be a big issue. We can still implement more specialized loaders in the future.
- Python to clean the data. Not sure which data cleaning component we want to provide out of the box. Input welcome.
- [LangChain](https://github.com/langchain-ai/langchain) for chunking & embedding like we already use. LlamaIndex mostly provides a wrapper on LangChain here and works with harder to handle nodes.
- [Weaviate](https://github.com/weaviate/weaviate) as vector store. It contains a lot of the RAG functionality built-in, which allows us to focus on the evaluation loop. We have worked with it before and can collaborate with the team behind it.
- [Ragas](https://github.com/explodinggradients/ragas) for evaluation. @Hakimovich99 looked into the available frameworks and this seems to be the best fit.

**Comment by Hakimovich99** [comment]
Thanks Robbe! Concerning LlamaIndex data loaders, here is an example of what you get using their PyMuPDFReader:
<img width="1094" alt="image" src="https://github.com/ml6team/fondant-usecase-RAG/assets/117269156/5c51c701-f8d2-4cef-b2d4-9f5b7b03d8fd">
When can decide based on that which data other than text we want to serialise.

**Comment by PhilippeMoussalli** [comment]
Thanks Robbe! Concerning the original pdfs we can either render it back in the viewer from: 

* The raw text extracted from the llama index loaders. Advantages is that it's lightweight and does not require extra work. Though most formatting will be lost (document structure, colors, tables, ...) 
* We encode it as a `base64` string in the loading document component and store that info in an extra column, this would enable us to render it back. The disadvantages here is that it's less lightweight as we're storing the data twice in different formats (llama doc + base64) 

From Bravo squad on PoAB: 

```
We started by trying out PyPDF library, but moved to Azure Form Recognizer Service as it was much better in extracting information from tables and other non-native PDF formatting structures.
``` 

Something to keep in mind on what are the sources we start from and how to extract information from them.

**Comment by RobbeSneyders** [comment]
I think the lightweight text visualization is a good start.

There's a bunch of PDF loaders. This one seems to be the most advanced, but uses an API in the back: https://llamahub.ai/l/smart_pdf_loader. Unfortunately the loader results are not documented very well, so it might be best to try them out and check which format they produce.

Otherwise, just looking for a general standard PDF representation and building a custom loader to generate that one could be an option as well.

**Comment by janvanlooyml6** [comment]
The more I think about it, the less I believe that creating an evaluation module as a Fondant pipeline (lower half of the diagram above) is a good idea.

I do not see any advantage tbh, except that we can say we can do evaluation in a Fondant pipeline. But that very much feels like a ‘when you are holding a hammer, everything looks like a nail argument’
I thought that querying the vector store in multiple configurable ways could be an advantage (above), but I no longer think so as none of the advantages of Fondant play a role. It can simply be tested in an evaluation script/library and/or notebook.

I see a lot of disadvantages though:

- We need to create an evaluation pipeline, which slows down our development with at least a week
- We will need to maintain and keep up to date an evaluation pipeline with functionality that is readily available in existing frameworks
  - A load/generate data component (creating synthetic test data is getting bigger)
  - A query component for different vector stores
  - An evaluation component for different evaluation frameworks (which are updated nearly daily) and metrics
- We are building something ‘in production’ while we do not know what it should look like. What we need to do is get a prototype out there (a Jupyter notebook) with some prepared functionality and develop it further while working on an actual use case with specialists trying to cater to their needs as much as we can. Once we know the best way of tackling the problem of evaluating RAG setups (test sets, eval metrics, visualizations etc) with different types of datasets (input data, language, task, data size etc.) and we somehow find a good reason to incorporate it in a Fondant pipeline, we can do it. Now, however, we are trying to fit the problem to a technology instead of vice versa and that will not work.
- Making it a Fondant pipeline will make it several times slower! A typical evaluation run takes a few minutes: loading the data a few seconds, querying the vector store a few seconds, evaluating the retrieved chunks a few seconds when using literal matching, a few minutes when using an LLM, aggregation a fraction of a second. 
- To this process we will be adding the startup time of four Fondant components which will probably be 20mins (5mins per component) when running in the cloud. Users will hate this, and rightly so as the benefits are unclear! When doing ten data runs it will add over three hours of compute time without a clear benefit. Moreover, there is also really no reason to run an eval pipeline every data run. It would be much more efficient processing all the runs at once. But even then a script would be fine as there is no oom data or lineage required on the eval pipeline side. None of the Fondant advantages play a role there, only its disadvantages.
- In  essence we will be competing with evaluation frameworks and RAG inference frameworks, two things we do not want to be and which are perfectly complementary with our goal of being the best data processing framework for production

It also does not really fit conceptually as the process of scheduling a number of runs and that of evaluating them with different test sets and metrics are two fundamentally separate processes. Joining a data run and an evaluation run at the waist totally defeats the purpose. Running one evaluation run per data run would not only be expensive in time and compute but it would also not fit the purpose. In many cases, as a data scientist or an ML engineer, you would want to run multiple pipelines before evaluating or evaluate multiple times with different datasets, metrics or evaluation frameworks after a certain number of runs. They are entirely separate things! We should make it as easy as possible to schedule and launch a number of RAG data pipelines in parallel on the one hand, and provide the most easy to use and most insightful way of understanding the results using Fondant’s unique characteristics on the other. For everything in between we should provide pointers to existing tools and propose workflows that were tested in real life by actual users.

**Comment by janvanlooyml6** [comment]
How I would propose to tackle the RAG eval use case would be to see the evaluation tooling script and tooling as something that takes advantage of the strengths of Fondant but operates outside of its core. (It can be packages that come with it or a separate repo building on top of it or just a notebook. We can decide later which is most practical).

The primary goal for the track right now should be to set up a notebook to launch pipelines and evaluate their performance as soon as possible. I think we have found an off-the-shelf labelled dataset and we have an eye on some metrics and evaluation frameworks so let’s use that for now and set it up as quickly as possible. Initially the runs can be launched manually or using a crude script. The important thing is to start experimenting as soon as possible and evaluate the work flow with colleagues who have actually worked on real-world data. This should be doable in a day or two. Hakim should be able to do this with some help from the core team.

At the same time it will be important to have all the relevant data preparation techniques (chunking - including summarization - and embedding mainly, some cleaning too) implemented in the main RAG pipeline so that they can be used in the evaluation process. Apparently data size is also a thing to understand performance so we might want to provide a way to select subsets of prepared data and push them to the vector store as separate runs. Anyhow, we need to determine how we are going to tackle this as soon as possible as this may take some work. Without the right techniques implemented there is no way to evaluate them.

What we also need to determine is how we are going to organize the search strategy and launch the runs. Fondant has quite a few tools in its belt to facilitate this such as caching but we need to determine how we are going to leverage this in the best possible way. Ideally a user would choose a number of parameters they want to try and a search strategy and possibly a number of runs when searching randomly. Then they should be able to launch these runs in parallel to the cloud, maybe overnight, while being able to monitor their progress. When they wake up they open a notebook, check the runs and start the eval script. They launch the data viewer and start checking what worked and what did not. They may want to test a few more parameter combinations so they define a few more runs and launch them. Later that day they again run the eval script over all the runs of two days and select the best one. They may want to test once more with a different evaluation framework and/or a holdout test set and try to visualize the results in a few more ways using different graph packages, try different query strategies perhaps. And then they are good to go. 
Anyway, got carried away a bit there but what we need to do is identify a strategy and implementation framework for hyperparameter search that fits Fondant and leverages its strengths, and test it in a notebook on actual runs. What we also need to do is make sure that it is very easy to track runs, make sure that we do not do any superfluous runs when defining a new search strategy and generally make it as easy as possible to get a clear overview of what is going on. The notebook can become something more sophisticated in terms of interface later on but for now it is perfect for our needs.

Once we have a clear view on all of the above and we are learning about the use case:  which metrics work when, which type of evaluations work when, whether synthetic test data works and/or when it does, which visualizations help things along, we should try to learn about best practices and tie them into the strongpoints of Fondant, especially lineage. We can show a lot of things other frameworks can only dream of so we should make sure the viewer caters to the RAG developers’ needs as well as possible. Personally I think a python library might be useful here to easily visualize etc. but I would decide that only when we have the feeling that we grasp the use case and know what developers want.
